import { Itodo, StatusKey, MenuObj } from 'types';
import uuidv4 from '../utils/getUuid';

export const TODOS: Itodo[] = [
  {
    id: uuidv4(),
    taskName: '기본세팅',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-08-24',
  },
  {
    id: uuidv4(),
    taskName: '원티드프로젝트',
    status: 'InProgress',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-08-25',
  },
  {
    id: uuidv4(),
    taskName: '자소서 쓰기',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-08-26',
  },
  {
    id: uuidv4(),
    taskName: '리드미 작성',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-08-27',
  },
  {
    id: uuidv4(),
    taskName: '거리 두기',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-08-28',
  },
  {
    id: uuidv4(),
    taskName: '회의',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-08-29',
  },
  {
    id: uuidv4(),
    taskName: '캐치마인드',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-08-30',
  },
  {
    id: uuidv4(),
    taskName: '백신 예약하기',
    status: 'Done',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-01',
  },
  {
    id: uuidv4(),
    taskName: '전입 신고',
    status: 'InProgress',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-02',
  },
  {
    id: uuidv4(),
    taskName: '기술 블로그 작성',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-03',
  },
  {
    id: uuidv4(),
    taskName: '집들이 선물사기',
    status: 'InProgress',
    priority: 'low',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-04',
  },
  {
    id: uuidv4(),
    taskName: '에어컨 수리',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-05',
  },
  {
    id: uuidv4(),
    taskName: '여름 이불 빨래',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-06',
  },
  {
    id: uuidv4(),
    taskName: '세션 회고 작성',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-07',
  },
  {
    id: uuidv4(),
    taskName: '주간 회고 작성',
    status: 'Done',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-08',
  },
  {
    id: uuidv4(),
    taskName: '맥북 구매',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-09',
  },
  {
    id: uuidv4(),
    taskName: '이력서 작성',
    status: 'Todo',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-10',
  },
  {
    id: uuidv4(),
    taskName: '물 2리터 마시기',
    status: 'InProgress',
    priority: 'low',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-11',
  },
  {
    id: uuidv4(),
    taskName: '제주 항공편 구매',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-12',
  },
  {
    id: uuidv4(),
    taskName: '영화 소개 웹 페이지 제작하기',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-13',
  },
  {
    id: uuidv4(),
    taskName: '프로젝트 피그마 시안 만들기',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-13',
  },
  {
    id: uuidv4(),
    taskName: '컨퍼런스 등록하기',
    status: 'Todo',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-13',
  },
  {
    id: uuidv4(),
    taskName: '코딩용 플레이리스트 만들기',
    status: 'Todo',
    priority: 'low',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-13',
  },
  {
    id: uuidv4(),
    taskName: '프로젝트 스크럼 정하기',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-14',
  },
  {
    id: uuidv4(),
    taskName: '타입스크립트 강의 듣기',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-14',
  },
  {
    id: uuidv4(),
    taskName: '2주차 스터디 과제하기',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-15',
  },
  {
    id: uuidv4(),
    taskName: '기술면접 클리닉 참여',
    status: 'Done',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-15',
  },
  {
    id: uuidv4(),
    taskName: '수영장 등록하기',
    status: 'Todo',
    priority: 'low',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-15',
  },
  {
    id: uuidv4(),
    taskName: '자바스크립트 완벽 가이드 1회독',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-15',
  },
  {
    id: uuidv4(),
    taskName: '오픈소스 등록하기',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '2021-09-16',
  },
];

export const STATUS: StatusKey[] = ['Todo', 'InProgress', 'Done'];

export const MENU: MenuObj = Object.freeze({
  PRIORITY: ['low', 'medium', 'high'],
  FILTER: ['Init', 'Deadline', 'Priority'],
});
