import { Itodo, StatusKey } from 'types';

export const TODOS: Itodo[] = [
  {
    id: 1,
    taskName: '기본세팅',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 2,
    taskName: '원티드프로젝트',
    status: 'InProgress',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 3,
    taskName: '자소서 쓰기',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 4,
    taskName: '리드미 작성',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 5,
    taskName: '거리 두기',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 6,
    taskName: '회의',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 7,
    taskName: '캐치마인드',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 8,
    taskName: '백신 예약하기',
    status: 'Done',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 9,
    taskName: '전입 신고',
    status: 'InProgress',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 10,
    taskName: '기술 블로그 작성',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 11,
    taskName: '집들이 선물사기',
    status: 'InProgress',
    priority: 'low',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 12,
    taskName: '에어컨 수리',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 13,
    taskName: '여름 이불 빨래',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 14,
    taskName: '세션 회고 작성',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 15,
    taskName: '주간 회고 작성',
    status: 'Done',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 16,
    taskName: '맥북 구매',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 17,
    taskName: '이력서 작성',
    status: 'Todo',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 18,
    taskName: '물 2리터 마시기',
    status: 'InProgress',
    priority: 'low',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 19,
    taskName: '제주 항공편 구매',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 20,
    taskName: '영화 소개 웹 페이지 제작하기',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 21,
    taskName: '프로젝트 피그마 시안 만들기',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 22,
    taskName: '컨퍼런스 등록하기',
    status: 'Todo',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 23,
    taskName: '코딩용 플레이리스트 만들기',
    status: 'Todo',
    priority: 'low',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 24,
    taskName: '프로젝트 스크럼 정하기',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 25,
    taskName: '타입스크립트 강의 듣기',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 26,
    taskName: '2주차 스터디 과제하기',
    status: 'InProgress',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 27,
    taskName: '기술면접 클리닉 참여',
    status: 'Done',
    priority: 'high',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 28,
    taskName: '수영장 등록하기',
    status: 'Todo',
    priority: 'low',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 29,
    taskName: '자바스크립트 완벽 가이드 1회독',
    status: 'Done',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
  {
    id: 30,
    taskName: '오픈소스 등록하기',
    status: 'Todo',
    priority: 'medium',
    createdAt: '',
    updatedAt: '',
    dueDate: '',
  },
];

export const STATUS: StatusKey[] = ['Todo', 'InProgress', 'Done'];
